logging:
  level:
    '[com.practicedidik.catalog]': TRACE 
spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    url: jdbc:postgresql://127.0.0.1/book_catalog
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
      
      
app:
  currency: IDR
  timezone: Asia/Jakarta
  welcome-text: Hello semuanya ini pertama latihan saya, Didik irawan!
cloud:
  cloud-key: ${CLOUD_KEY}
server:
  port: 8081
  
---
spring:
  config:
    activate:
      on-profile:
      - development 
       
server:
  port: 8082
  
app:
  welcome-text: Hallo ini didik, ini server development


---
spring:
  config:
    activate:
      on-profile:
      - test
  
server:
  port: 8090
  
 
---
spring:
  config:
    activate:
      on-profile:
      - prod
  
server:
  port: 8083
